In [1]:
import numpy as np

In [2]:
#Create array using list
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
x.dtype

dtype('int64')

In [5]:
x = np.array([1,2,3,4], dtype=np.int64)

In [6]:
#Array length
x.shape

(4,)

In [7]:
#Create two-dimentional array
m = np.array([[2,3,4],[5,6,7]])

In [8]:
m.shape

(2, 3)

In [9]:
m

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
#Create array using built-in functions
#ones - fill by zero
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(2)

array([0., 0.])

In [13]:
#Единичная матрица
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.random((2,3))

array([[0.5977541 , 0.24596003, 0.89609065],
       [0.85198324, 0.64621271, 0.36502979]])

In [17]:
#Обращение по индексу
x[1]

2

In [18]:
y = np.array([[1,2,3,4],[2,3,4,56]])

In [19]:
y

array([[ 1,  2,  3,  4],
       [ 2,  3,  4, 56]])

In [20]:
#Вторая строка, четвертый столбец
y[1,3]

56

In [21]:
y[:,:3]

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
#Задача. Вытащить из массива 'y' все значения больше 2. Создать маску:
y > 2

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [23]:
y[y > 2]

array([ 3,  4,  3,  4, 56])

In [24]:
#flatten, reshape
b = np.array([[1,3,4,4,5], [2,3,4,56,5]])

In [25]:
b

array([[ 1,  3,  4,  4,  5],
       [ 2,  3,  4, 56,  5]])

In [26]:
#Преобразовать в одномерный массив
b.flatten()

array([ 1,  3,  4,  4,  5,  2,  3,  4, 56,  5])

In [28]:
#Транспонирование матрицы
b.T

array([[ 1,  2],
       [ 3,  3],
       [ 4,  4],
       [ 4, 56],
       [ 5,  5]])

In [29]:
#Изменение размерности массива (change ONLY shape)
b.reshape(10,1)

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [30]:
#resize меняет исходный массив
b.resize(10,1)

In [31]:
b

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [32]:
#Операции над векторами
v = np.array([9,10])
w = np.array([11,12])

In [33]:
v + w

array([20, 22])

In [34]:
# Или
np.add(v, w)

array([20, 22])

In [35]:
#Разность векторов
v - w

array([-2, -2])

In [36]:
np.subtract(v, w)

array([-2, -2])

In [37]:
# Умножение
v * w

array([ 99, 120])

In [38]:
np.multiply(v, w)

array([ 99, 120])

In [39]:
# Скалярное произведение двух векторов
np.dot(v, w)

219